### ISSUE TITLE
CUDA error: no kernel image on RTX Pro 4000 Ada (Arch 8.9)

### ISSUE THREAD

**Issue by iiizen** [NVlabs/alpasim#37]
"My SensorSim crashes with CUDA error: no kernel image on RTX 4000 Ada (Arch 8.9). The docker image seems to lack support for Ada architecture. Is there an updated image?"
please help thx alot

**Comment by iiizen** [comment]
Hi  @daehyoungko,

Thanks for the reply. However, the issue I am encountering is not an Out-of-Memory (OOM) error.

The crash happens specifically with the error no kernel image is available for execution on the device. This indicates an architecture mismatch. It appears that the pre-compiled nvidia-nurec-grpc:0.2.0 docker image (specifically the TinyCUDA-NN module inside) was compiled for sm_80 (A100) or sm_90 (H100), but completely lacks the binary code for Compute Capability 8.9 (Ada Lovelace architecture).

Because of this missing architecture flag during your build process, the kernel fails to load on any RTX 4000/6000 Ada GPUs, regardless of how much VRAM they have. Since the NuRec SensorSim component is closed-source docker image, I cannot recompile it locally for sm_89 (unlike the rest of the open-source Alpasim components, which I have already successfully built and run on my local machine by bypassing the renderer).

My question is: > Could the team please consider adding sm_89 to your TORCH_CUDA_ARCH_LIST (or equivalent build flags) and releasing an updated nvidia-nurec-grpc image? Or alternatively, is there a way for us to build the SensorSim component from source?

Thanks again for your time and the great work on Alpasim!

> "You need an NVIDIA GPU with at least 24 GB VRAM for inference. Tested configurations include RTX 3090, A100, and H100. Running on GPUs with less memory (e.g., 16 GB) will likely result in CUDA out-of-memory errors."
> 
> It is from https://github.com/NVlabs/alpamayo?tab=readme-ov-file#frequently-asked-questions-faq and it is applicable to alpasim as well.

**Comment by daehyoungko** [comment]
My setup has following, and it works at my end, Can you please try cuda version 12.X rather than 13.1? I assume that this issue is due to cuda version conflict.
Nvidia driver version : 535.274.02
CUDA Version :12.2
GPU :NVIDIA RTX 6000 Ada

**Comment by iiizen** [comment]
> My setup has following, and it works at my end, Can you please try cuda version 12.X rather than 13.1? I assume that this issue is due to cuda version conflict. Nvidia driver version : 535.274.02 CUDA Version :12.2 GPU :NVIDIA RTX 6000 Ada

Hi @daehyoungko,

Thank you for the suggestion and sharing your setup!

I double-checked my hardware and realized my GPU is actually the newer NVIDIA RTX PRO 4000 Blackwell generation (not the Ada generation).

Currently, my host is using driver version 590.48.01 with CUDA 13.1. Since Blackwell is a newer architecture, I cannot downgrade my driver to 535.274.02 as the older driver would not recognize this new GPU.

Could you confirm if the current sensorsim Docker image has been compiled with support for the Blackwell architecture (Compute Capability 12.0)? If not, is there any workaround or an ETA for Blackwell support?

Thank you!
